name: "VBA Build"
description: "Build VBA-Enabled Office documents from source code using GitHub Actions."

branding:
  icon: 'code'
  color: 'blue' 

runs:
  using: "composite"
  steps:
    - name: "Install 7-zip"
      shell: pwsh
      run: choco install 7zip.install
    # https://community.chocolatey.org/packages?q=Excel
    - name: "Installing Office 365 (takes about 5 minutes...)"
      shell: pwsh
      run: choco install office365proplus -y
    - name: "Run VBA Build"
      shell: pwsh
      run: '${{ github.action_path }}\Main.ps1'
outputs:
  result:
    description: "The result of the VBA build process."
    value: "success"
