name: Test Build VBA (macOS)
on:
  workflow_dispatch:
  push:
    branches:
      - mac

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Office"
        run: |
          sudo installer -pkg microsoft_office_2016_installer.pkg -target /.
        shell: bash
      - name: "Create screenshots directory and take screenshot"
        run: |
          mkdir -p screenshots
          screencapture -x screenshots/$(date +%Y%m%d_%H%M%S).png
        shell: bash
      - name: "Upload Screenshots"
        # Run this step even if the build failed
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "Screenshots"
          path: "./screenshots/*"
          if-no-files-found: warn