name: Rubberduck
on:
  workflow_dispatch:
jobs:   
  install-rubberduck:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        
      - name: "Install Rubberduck"
        run: |
          # Install Rubberduck
          . "./scripts/Install-Rubberduck-VBA.ps1"
