#Create a simple workflow to take a screenshot of the Windows worker's desktop
name: Screenshot
on:
  workflow_dispatch:
jobs:   
  screenshot:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Take Screenshot"
        run: |
          # Take a screenshot of the Office application
          . "./scripts/utils/Screenshot.ps1"
          Take-Screenshot -OutputPath $outputDir + "Screenshot_${fileNameNoExt}.png"
      - name: "Upload Screenshot"
        uses: actions/upload-artifact@v4
        with:
          name: "Screenshot"
          path: "screenshot.png"