#Create a simple workflow to take a screenshot of the Windows worker's desktop
name: Screenshot
on:
  workflow_dispatch:
jobs:   
  screenshot:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Take Screenshot"
        run: |
          # Minimize the CMD window
          . "./scripts/utils/Minimize.ps1"
          Minimize-Window "Administrator: C:\actions"
          # Take a screenshot of the Office application
          . "./scripts/utils/Screenshot.ps1"
          Take-Screenshot -OutputPath "Screenshot.png"
      - name: "Upload Screenshot"
        uses: actions/upload-artifact@v4
        with:
          name: "Screenshot"
          path: "screenshot.png"