# https://github.com/durs/node-activex/blob/d7a13a0b030af1783779be3b39f4672d1f26569c/.github/workflows/ci.yml#L23
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: ci
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['22.x']
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      # https://community.chocolatey.org/packages?q=Excel
      - name: "Installing Office 365 takes about 5 minutes..."
        run: choco install office365proplus
      - name: Run VBScript
        shell: cmd
        # To avoid displaying the header: run: cscript //nologo test.vbs
        run: cscript ./test.vbs 
        
      # - run: |
      #    npm install -g mocha
      #    # mocha --expose-gc test  # Three tests will fail!
      #- run: npm test