name: Test Build VBA
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Build VBA-Enabled Workbook (using own action)"
        uses: ./
        with:
          sourceDir: "./tests"
      - name: "Upload Build Artifact"
        uses: actions/upload-artifact@v4
        id: "upload"
        with:
          name: "VBA-Enabled-Documents"
          path: "./tests/out/*"
          if-no-files-found: warn
      - name: "Upload Screenshots"
        uses: actions/upload-artifact@v4
        with:
          name: "Screenshots"
          path: "./tests/screenshots/*"
          if-no-files-found: warn
      - name: "Attestation"
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "VBA-Enabled-Documents"
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}